version: '3'

services:
    web:
        build: ./web
        ports:
          - 80:80

    redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - data:/data

volumes:
    data: